import { useCallback, useEffect, useMemo, useState } from "react";
import { LanguageContext } from "./languageContext";

const LANGUAGE_STORAGE_KEY = "green_quiz_language";
const supportedLanguages = ["ru", "en", "fr"];

const translations = {
    ru: {
        "nav.home": "Главная",
        "nav.dashboard": "Кабинет",
        "nav.profile": "Профиль",
        "meta.home": "Главная",
        "meta.login": "Вход",
        "meta.register": "Регистрация",
        "meta.profile": "Профиль",
        "meta.dashboard": "Кабинет",
        "meta.createQuiz": "Создание квиза",
        "meta.editQuiz": "Редактирование квиза",
        "meta.liveRoom": "Live-комната",
        "meta.history": "История",
        "meta.join": "Вход по коду",
        "dashboard.title": "Кабинет",
        "dashboard.organizer": "Организатор",
        "dashboard.participant": "Участник",
        "dashboard.myQuizzes": "Мои квизы",
        "dashboard.createQuiz": "Создать квиз",
        "dashboard.history": "История",
        "dashboard.join": "Присоединиться",
        "dashboard.gameHistory": "История игр",
        "join.title": "Присоединиться по коду",
        "join.subtitle": "Введите код комнаты и попадите в активный квиз после запуска организатором.",
        "join.submit": "Войти в комнату",
        "join.submitting": "Вход...",
        "history.title": "История игр",
        "history.subtitle": "После прохождения квизов здесь будут баллы, места в лидерборде и даты участия.",
        "history.loading": "Загрузка истории...",
        "history.empty": "История участника пока пуста.",
        "history.answersAndCode": "Ответов: {answers}, код комнаты: {code}",
        "history.place": "{place} место",
        "history.score": "{score} баллов",
        "history.placeColumn": "Место",
        "history.participantColumn": "Участник",
        "history.correctColumn": "Верно",
        "history.scoreColumn": "Баллы",
        "organizerHistory.title": "История проведенных квизов",
        "organizerHistory.subtitle": "Результаты завершенных комнат, число участников и победители.",
        "organizerHistory.error": "Не удалось загрузить историю.",
        "organizerHistory.empty": "Проведенные игры появятся после завершения комнаты.",
        "organizerHistory.roomInfo": "Код {code}, участников: {count}",
        "organizerHistory.finished": "Завершен",
        "home.subtitle": "Проводите квизы в реальном времени: участники входят по коду, отвечают на таймере, а результаты собираются в понятный лидерборд.",
        "home.toDashboard": "В кабинет",
        "home.createQuiz": "Создать квиз",
        "home.myHistory": "Моя история",
        "home.startGame": "Начать игру",
        "home.login": "Войти",
        "home.weeklyLeaderboard": "Лидерборд недели",
        "home.activeParticipants": "Самые активные участники",
        "home.quizzesCount": "{count} квизов",
        "home.points": "баллов",
        "home.leaderboard.1": "Алина",
        "home.leaderboard.2": "Марк",
        "home.leaderboard.3": "София",
        "home.leaderboard.4": "Илья",
        "home.stage.1.title": "Соберите раунд",
        "home.stage.1.text": "Добавьте вопросы, картинки, варианты и настройте показ правильных ответов.",
        "home.stage.2.title": "Запустите аудиторию",
        "home.stage.2.text": "Комната откроется по коду, а старт станет доступен после входа участников.",
        "home.stage.3.title": "Разберите итог",
        "home.stage.3.text": "Система покажет топ игроков, личное место и сохранит историю прохождения.",
        "organizerQuizzes.title": "Мои квизы",
        "organizerQuizzes.subtitle": "Управляйте черновиками и готовыми квизами.",
        "organizerQuizzes.loading": "Загрузка квизов...",
        "organizerQuizzes.emptyTitle": "Квизов пока нет",
        "organizerQuizzes.emptyText": "Создайте первый квиз, добавьте вопросы и сохраните черновик.",
        "organizerQuizzes.questions": "{count} вопросов",
        "organizerQuizzes.room": "Комната",
        "organizerQuizzes.creating": "Создание...",
        "organizerQuizzes.edit": "Редактировать",
        "organizerQuizzes.deleting": "Удаление...",
        "common.cancel": "Отмена",
        "common.confirm": "Подтвердить",
        "common.optional": "Опционально",
        "common.loading": "Загрузка...",
        "common.remove": "Удалить",
        "common.save": "Сохранить",
        "common.language": "Язык",
        "common.theme": "Тема интерфейса",
        "theme.light": "Светлая",
        "theme.dark": "Темная",
        "theme.toLight": "Включить светлую тему",
        "theme.toDark": "Включить темную тему",
        "profile.title": "Профиль",
        "profile.subtitle": "Измените имя, аватарку и настройки интерфейса.",
        "profile.toDashboard": "В кабинет",
        "profile.name": "Имя",
        "profile.role": "Роль",
        "profile.avatar.choose": "Выбрать аватар",
        "profile.avatar.uploading": "Загрузка...",
        "profile.saved": "Профиль сохранен.",
        "profile.save": "Сохранить профиль",
        "profile.saving": "Сохранение...",
        "profile.logout": "Выйти из аккаунта",
        "profile.logoutConfirm.title": "Выйти из аккаунта?",
        "profile.logoutConfirm.text": "После выхода вы вернетесь на главную страницу.",
        "quiz.error.save": "Не удалось сохранить квиз.",
        "quiz.createTitle": "Создать квиз",
        "quiz.createSubtitle": "Задайте параметры квиза, добавьте вопросы, варианты ответов и отметьте правильные ответы.",
        "quiz.editTitle": "Редактировать квиз",
        "quiz.editSubtitle": "Измените параметры, вопросы и варианты ответов. Сохранение заменит текущий набор вопросов.",
        "quiz.loading": "Загрузка квиза...",
        "quiz.saveQuiz": "Сохранить квиз",
        "quiz.saveChanges": "Сохранить изменения",
        "quiz.title": "Название квиза",
        "quiz.titlePlaceholder": "Например: Frontend Battle",
        "quiz.time": "Время на вопрос",
        "quiz.timeHelp": "Указывается в секундах для каждого вопроса.",
        "quiz.category": "Категория",
        "quiz.categoryPlaceholder": "Веб-разработка",
        "quiz.status": "Статус",
        "quiz.status.draft": "Черновик",
        "quiz.status.ready": "Готов",
        "quiz.showResults": "Показывать результаты участникам",
        "quiz.showResultsHelp": "Участники увидят правильность ответа, баллы и общий лидерборд. Если выключить, подробные результаты останутся только у организатора.",
        "quiz.description": "Описание",
        "quiz.questions": "Вопросы",
        "quiz.question": "Вопрос",
        "quiz.questionText": "Текст вопроса",
        "quiz.questionImage": "Изображение вопроса",
        "quiz.type": "Тип",
        "quiz.type.single": "Один ответ",
        "quiz.type.multiple": "Несколько ответов",
        "quiz.correct": "Правильный",
        "quiz.option": "Вариант",
        "quiz.optionImage": "Изображение",
        "quiz.addOption": "Добавить вариант",
        "quiz.addQuestion": "Добавить вопрос",
        "quiz.rules": "Правила",
        "quiz.uploadHelp": "Выберите файл, перетащите картинку или вставьте из буфера. Файл сохранится на сервере.",
        "quiz.uploadChoose": "Выбрать",
        "quiz.uploading": "Загрузка...",
        "quiz.uploadRemove": "Убрать",
        "quiz.saving": "Сохранение...",
        "quiz.validation.title": "Заполните обязательные поля",
        "quiz.validation.quizTitle": "Не указано название квиза.",
        "quiz.validation.timeLimit": "Укажите время на вопрос от 5 до 600 секунд.",
        "quiz.validation.questionText": "В вопросе {question} не указан текст.",
        "quiz.validation.optionContent": "В вопросе {question}, варианте {option} нужен текст или изображение.",
        "quiz.validation.singleCorrect": "В вопросе {question} отметьте ровно один правильный вариант.",
        "quiz.validation.multipleCorrect": "В вопросе {question} отметьте минимум один правильный вариант.",
        "quiz.deleteQuestion.title": "Удалить вопрос?",
        "quiz.deleteQuestion.text": "Вопрос и все его варианты будут удалены из формы.",
        "quiz.deleteOption.title": "Удалить вариант?",
        "quiz.deleteOption.text": "Вариант ответа будет удален из этого вопроса.",
        "quiz.deleteQuiz.title": "Удалить квиз?",
        "quiz.deleteQuiz.text": "Квиз будет удален без возможности восстановления.",
    },
    en: {
        "nav.home": "Home",
        "nav.dashboard": "Dashboard",
        "nav.profile": "Profile",
        "meta.home": "Home",
        "meta.login": "Login",
        "meta.register": "Register",
        "meta.profile": "Profile",
        "meta.dashboard": "Dashboard",
        "meta.createQuiz": "Create quiz",
        "meta.editQuiz": "Edit quiz",
        "meta.liveRoom": "Live room",
        "meta.history": "History",
        "meta.join": "Join by code",
        "dashboard.title": "Dashboard",
        "dashboard.organizer": "Organizer",
        "dashboard.participant": "Participant",
        "dashboard.myQuizzes": "My quizzes",
        "dashboard.createQuiz": "Create quiz",
        "dashboard.history": "History",
        "dashboard.join": "Join",
        "dashboard.gameHistory": "Game history",
        "join.title": "Join by code",
        "join.subtitle": "Enter the room code and join the live quiz after the organizer starts it.",
        "join.submit": "Join room",
        "join.submitting": "Joining...",
        "history.title": "Game history",
        "history.subtitle": "After quizzes, your points, leaderboard places, and participation dates appear here.",
        "history.loading": "Loading history...",
        "history.empty": "Participant history is empty.",
        "history.answersAndCode": "Answers: {answers}, room code: {code}",
        "history.place": "{place} place",
        "history.score": "{score} points",
        "history.placeColumn": "Place",
        "history.participantColumn": "Participant",
        "history.correctColumn": "Correct",
        "history.scoreColumn": "Points",
        "organizerHistory.title": "Hosted quiz history",
        "organizerHistory.subtitle": "Results from finished rooms, participant counts, and winners.",
        "organizerHistory.error": "Could not load history.",
        "organizerHistory.empty": "Hosted games will appear after a room is finished.",
        "organizerHistory.roomInfo": "Code {code}, participants: {count}",
        "organizerHistory.finished": "Finished",
        "home.subtitle": "Run real-time quizzes: players join by code, answer on a timer, and results land in a clear leaderboard.",
        "home.toDashboard": "Dashboard",
        "home.createQuiz": "Create quiz",
        "home.myHistory": "My history",
        "home.startGame": "Start playing",
        "home.login": "Log in",
        "home.weeklyLeaderboard": "Weekly leaderboard",
        "home.activeParticipants": "Most active players",
        "home.quizzesCount": "{count} quizzes",
        "home.points": "points",
        "home.leaderboard.1": "Ava",
        "home.leaderboard.2": "Mark",
        "home.leaderboard.3": "Sofia",
        "home.leaderboard.4": "Leo",
        "home.stage.1.title": "Build the round",
        "home.stage.1.text": "Add questions, images, answer options, and configure how correct answers are shown.",
        "home.stage.2.title": "Launch the room",
        "home.stage.2.text": "Players enter by code, and the start unlocks after participants join.",
        "home.stage.3.title": "Review the result",
        "home.stage.3.text": "The system shows top players, personal rank, and saves play history.",
        "organizerQuizzes.title": "My quizzes",
        "organizerQuizzes.subtitle": "Manage drafts and ready quizzes.",
        "organizerQuizzes.loading": "Loading quizzes...",
        "organizerQuizzes.emptyTitle": "No quizzes yet",
        "organizerQuizzes.emptyText": "Create your first quiz, add questions, and save the draft.",
        "organizerQuizzes.questions": "{count} questions",
        "organizerQuizzes.room": "Room",
        "organizerQuizzes.creating": "Creating...",
        "organizerQuizzes.edit": "Edit",
        "organizerQuizzes.deleting": "Deleting...",
        "common.cancel": "Cancel",
        "common.confirm": "Confirm",
        "common.optional": "Optional",
        "common.loading": "Loading...",
        "common.remove": "Delete",
        "common.save": "Save",
        "common.language": "Language",
        "common.theme": "Interface theme",
        "theme.light": "Light",
        "theme.dark": "Dark",
        "theme.toLight": "Switch to light theme",
        "theme.toDark": "Switch to dark theme",
        "profile.title": "Profile",
        "profile.subtitle": "Update your name, avatar, and interface settings.",
        "profile.toDashboard": "Dashboard",
        "profile.name": "Name",
        "profile.role": "Role",
        "profile.avatar.choose": "Choose avatar",
        "profile.avatar.uploading": "Uploading...",
        "profile.saved": "Profile saved.",
        "profile.save": "Save profile",
        "profile.saving": "Saving...",
        "profile.logout": "Log out",
        "profile.logoutConfirm.title": "Log out?",
        "profile.logoutConfirm.text": "You will return to the home page.",
        "quiz.error.save": "Could not save the quiz.",
        "quiz.createTitle": "Create quiz",
        "quiz.createSubtitle": "Set quiz parameters, add questions and answers, and mark correct options.",
        "quiz.editTitle": "Edit quiz",
        "quiz.editSubtitle": "Change parameters, questions, and answers. Saving will replace the current question set.",
        "quiz.loading": "Loading quiz...",
        "quiz.saveQuiz": "Save quiz",
        "quiz.saveChanges": "Save changes",
        "quiz.title": "Quiz title",
        "quiz.titlePlaceholder": "Example: Frontend Battle",
        "quiz.time": "Time per question",
        "quiz.timeHelp": "Measured in seconds for each question.",
        "quiz.category": "Category",
        "quiz.categoryPlaceholder": "Web development",
        "quiz.status": "Status",
        "quiz.status.draft": "Draft",
        "quiz.status.ready": "Ready",
        "quiz.showResults": "Show results to participants",
        "quiz.showResultsHelp": "Participants will see answer correctness, points, and the leaderboard. If disabled, detailed results stay organizer-only.",
        "quiz.description": "Description",
        "quiz.questions": "Questions",
        "quiz.question": "Question",
        "quiz.questionText": "Question text",
        "quiz.questionImage": "Question image",
        "quiz.type": "Type",
        "quiz.type.single": "Single answer",
        "quiz.type.multiple": "Multiple answers",
        "quiz.correct": "Correct",
        "quiz.option": "Option",
        "quiz.optionImage": "Image",
        "quiz.addOption": "Add option",
        "quiz.addQuestion": "Add question",
        "quiz.rules": "Rules",
        "quiz.uploadHelp": "Choose a file, drag an image, or paste it from the clipboard. The file will be saved on the server.",
        "quiz.uploadChoose": "Choose",
        "quiz.uploading": "Uploading...",
        "quiz.uploadRemove": "Remove",
        "quiz.saving": "Saving...",
        "quiz.validation.title": "Fill in the required fields",
        "quiz.validation.quizTitle": "Quiz title is missing.",
        "quiz.validation.timeLimit": "Set question time from 5 to 600 seconds.",
        "quiz.validation.questionText": "Question {question} is missing text.",
        "quiz.validation.optionContent": "Question {question}, option {option} needs text or an image.",
        "quiz.validation.singleCorrect": "Question {question} must have exactly one correct option.",
        "quiz.validation.multipleCorrect": "Question {question} must have at least one correct option.",
        "quiz.deleteQuestion.title": "Delete question?",
        "quiz.deleteQuestion.text": "The question and all of its options will be removed from the form.",
        "quiz.deleteOption.title": "Delete option?",
        "quiz.deleteOption.text": "This answer option will be removed from the question.",
        "quiz.deleteQuiz.title": "Delete quiz?",
        "quiz.deleteQuiz.text": "This quiz will be permanently deleted.",
    },
    fr: {
        "nav.home": "Accueil",
        "nav.dashboard": "Tableau",
        "nav.profile": "Profil",
        "meta.home": "Accueil",
        "meta.login": "Connexion",
        "meta.register": "Inscription",
        "meta.profile": "Profil",
        "meta.dashboard": "Tableau",
        "meta.createQuiz": "Creation du quiz",
        "meta.editQuiz": "Modification du quiz",
        "meta.liveRoom": "Salle live",
        "meta.history": "Historique",
        "meta.join": "Code d'acces",
        "dashboard.title": "Tableau",
        "dashboard.organizer": "Organisateur",
        "dashboard.participant": "Participant",
        "dashboard.myQuizzes": "Mes quiz",
        "dashboard.createQuiz": "Creer un quiz",
        "dashboard.history": "Historique",
        "dashboard.join": "Rejoindre",
        "dashboard.gameHistory": "Historique",
        "join.title": "Rejoindre avec un code",
        "join.subtitle": "Entrez le code de la salle et rejoignez le quiz quand l'organisateur le lance.",
        "join.submit": "Rejoindre la salle",
        "join.submitting": "Connexion...",
        "history.title": "Historique des jeux",
        "history.subtitle": "Apres les quiz, vos points, vos places et les dates de participation apparaissent ici.",
        "history.loading": "Chargement de l'historique...",
        "history.empty": "L'historique du participant est vide.",
        "history.answersAndCode": "Reponses : {answers}, code : {code}",
        "history.place": "{place} place",
        "history.score": "{score} points",
        "history.placeColumn": "Place",
        "history.participantColumn": "Participant",
        "history.correctColumn": "Correct",
        "history.scoreColumn": "Points",
        "organizerHistory.title": "Historique des quiz animes",
        "organizerHistory.subtitle": "Resultats des salles terminees, nombre de participants et gagnants.",
        "organizerHistory.error": "Impossible de charger l'historique.",
        "organizerHistory.empty": "Les jeux animes apparaitront apres la fin d'une salle.",
        "organizerHistory.roomInfo": "Code {code}, participants : {count}",
        "organizerHistory.finished": "Termine",
        "home.subtitle": "Animez des quiz en temps reel : les joueurs entrent avec un code, repondent au chronometre et les resultats arrivent dans un classement clair.",
        "home.toDashboard": "Tableau",
        "home.createQuiz": "Creer un quiz",
        "home.myHistory": "Mon historique",
        "home.startGame": "Commencer",
        "home.login": "Connexion",
        "home.weeklyLeaderboard": "Classement de la semaine",
        "home.activeParticipants": "Participants les plus actifs",
        "home.quizzesCount": "{count} quiz",
        "home.points": "points",
        "home.leaderboard.1": "Ava",
        "home.leaderboard.2": "Marc",
        "home.leaderboard.3": "Sofia",
        "home.leaderboard.4": "Leo",
        "home.stage.1.title": "Preparez la manche",
        "home.stage.1.text": "Ajoutez des questions, des images, des options et configurez l'affichage des bonnes reponses.",
        "home.stage.2.title": "Lancez la salle",
        "home.stage.2.text": "Les joueurs entrent avec un code et le depart devient disponible apres leur arrivee.",
        "home.stage.3.title": "Analysez le resultat",
        "home.stage.3.text": "Le systeme affiche les meilleurs joueurs, la place personnelle et conserve l'historique.",
        "organizerQuizzes.title": "Mes quiz",
        "organizerQuizzes.subtitle": "Gerez les brouillons et les quiz prets.",
        "organizerQuizzes.loading": "Chargement des quiz...",
        "organizerQuizzes.emptyTitle": "Aucun quiz",
        "organizerQuizzes.emptyText": "Creez votre premier quiz, ajoutez des questions et enregistrez le brouillon.",
        "organizerQuizzes.questions": "{count} questions",
        "organizerQuizzes.room": "Salle",
        "organizerQuizzes.creating": "Creation...",
        "organizerQuizzes.edit": "Modifier",
        "organizerQuizzes.deleting": "Suppression...",
        "common.cancel": "Annuler",
        "common.confirm": "Confirmer",
        "common.optional": "Optionnel",
        "common.loading": "Chargement...",
        "common.remove": "Supprimer",
        "common.save": "Enregistrer",
        "common.language": "Langue",
        "common.theme": "Theme de l'interface",
        "theme.light": "Clair",
        "theme.dark": "Sombre",
        "theme.toLight": "Activer le theme clair",
        "theme.toDark": "Activer le theme sombre",
        "profile.title": "Profil",
        "profile.subtitle": "Modifiez votre nom, votre avatar et les reglages de l'interface.",
        "profile.toDashboard": "Tableau",
        "profile.name": "Nom",
        "profile.role": "Role",
        "profile.avatar.choose": "Choisir un avatar",
        "profile.avatar.uploading": "Chargement...",
        "profile.saved": "Profil enregistre.",
        "profile.save": "Enregistrer le profil",
        "profile.saving": "Enregistrement...",
        "profile.logout": "Se deconnecter",
        "profile.logoutConfirm.title": "Se deconnecter ?",
        "profile.logoutConfirm.text": "Vous reviendrez a la page d'accueil.",
        "quiz.error.save": "Impossible d'enregistrer le quiz.",
        "quiz.createTitle": "Creer un quiz",
        "quiz.createSubtitle": "Definissez les parametres, ajoutez les questions et marquez les bonnes reponses.",
        "quiz.editTitle": "Modifier le quiz",
        "quiz.editSubtitle": "Modifiez les parametres, les questions et les reponses. L'enregistrement remplacera la liste actuelle.",
        "quiz.loading": "Chargement du quiz...",
        "quiz.saveQuiz": "Enregistrer le quiz",
        "quiz.saveChanges": "Enregistrer les modifications",
        "quiz.title": "Titre du quiz",
        "quiz.titlePlaceholder": "Exemple : Frontend Battle",
        "quiz.time": "Temps par question",
        "quiz.timeHelp": "Indique en secondes pour chaque question.",
        "quiz.category": "Categorie",
        "quiz.categoryPlaceholder": "Developpement web",
        "quiz.status": "Statut",
        "quiz.status.draft": "Brouillon",
        "quiz.status.ready": "Pret",
        "quiz.showResults": "Afficher les resultats aux participants",
        "quiz.showResultsHelp": "Les participants verront la justesse des reponses, les points et le classement. Sinon, les details restent reserves a l'organisateur.",
        "quiz.description": "Description",
        "quiz.questions": "Questions",
        "quiz.question": "Question",
        "quiz.questionText": "Texte de la question",
        "quiz.questionImage": "Image de la question",
        "quiz.type": "Type",
        "quiz.type.single": "Une reponse",
        "quiz.type.multiple": "Plusieurs reponses",
        "quiz.correct": "Correct",
        "quiz.option": "Option",
        "quiz.optionImage": "Image",
        "quiz.addOption": "Ajouter une option",
        "quiz.addQuestion": "Ajouter une question",
        "quiz.rules": "Regles",
        "quiz.uploadHelp": "Choisissez un fichier, glissez une image ou collez-la depuis le presse-papiers. Le fichier sera enregistre sur le serveur.",
        "quiz.uploadChoose": "Choisir",
        "quiz.uploading": "Chargement...",
        "quiz.uploadRemove": "Retirer",
        "quiz.saving": "Enregistrement...",
        "quiz.validation.title": "Remplissez les champs obligatoires",
        "quiz.validation.quizTitle": "Le titre du quiz est manquant.",
        "quiz.validation.timeLimit": "Indiquez un temps par question entre 5 et 600 secondes.",
        "quiz.validation.questionText": "La question {question} n'a pas de texte.",
        "quiz.validation.optionContent": "Question {question}, option {option} : ajoutez un texte ou une image.",
        "quiz.validation.singleCorrect": "La question {question} doit avoir exactement une bonne reponse.",
        "quiz.validation.multipleCorrect": "La question {question} doit avoir au moins une bonne reponse.",
        "quiz.deleteQuestion.title": "Supprimer la question ?",
        "quiz.deleteQuestion.text": "La question et toutes ses options seront supprimees du formulaire.",
        "quiz.deleteOption.title": "Supprimer l'option ?",
        "quiz.deleteOption.text": "Cette option de reponse sera supprimee de la question.",
        "quiz.deleteQuiz.title": "Supprimer le quiz ?",
        "quiz.deleteQuiz.text": "Ce quiz sera supprime definitivement.",
    },
};

function readStoredLanguage() {
    const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return supportedLanguages.includes(storedLanguage) ? storedLanguage : "ru";
}

export function LanguageProvider({ children }) {
    const [language, setLanguageState] = useState(readStoredLanguage);

    useEffect(() => {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
        document.documentElement.lang = language;
    }, [language]);

    const setLanguage = useCallback((nextLanguage) => {
        setLanguageState(supportedLanguages.includes(nextLanguage) ? nextLanguage : "ru");
    }, []);

    const t = useCallback((key, values = {}) => {
        const template = translations[language]?.[key] ?? translations.ru[key] ?? key;
        return Object.entries(values).reduce(
            (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
            template,
        );
    }, [language]);

    const value = useMemo(
        () => ({ language, setLanguage, supportedLanguages, t }),
        [language, setLanguage, t],
    );

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
